# Generated by Django 6.0.3 on 2026-04-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
