# Generated by Django 6.0.3 on 2026-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_reciever_transaction_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
